### ISSUE TITLE
Pebble does not load album info

### ISSUE THREAD

**Issue by mrwhale** [Sorunome/pebble-mpd-client#1]
Hey dude! Really nice app, I've been waiting for something like this to pop up for the pebble! 

The app does not seem to load album info, or current status of the mpd server

When loading the app i just get the "loading..." message, however pressing any of the action buttons actually sends the commands and changes/pause/plays the server

Here are the pebble logs (probably not very useful) when loading the app

```
[20:05:44] le-mpd-client.c:374> Inited app
[20:05:45] javascript> MPD Client:392 loadScript /data/user/0/com.getpebble.android.basalt/app_js_app_files/40bd2917-1f73-462c-b428-147ba02cb9d7/pebble-js-app.js
[20:05:45] javascript> MPD Client:372 signalLoaded
[20:05:45] javascript> MPD Client:374 inside try-bridge-active
[20:05:45] javascript> MPD Client:383 signalLoaded (finalized)
[20:05:45] le-mpd-client.c:159> Recieved some message....
[20:05:45] le-mpd-client.c:167> JS is ready! App Timeout: 120
```

The mpd server is pi music box v0.6, but works successfully with other mpd clients (such as MPDroid, or ncmpcpp). Once i've finished off my pebble app and released v1.0 i'll come and contribute here!

**Comment by Sorunome** [comment]
Does the icon in the lower-left corner update accordingly to if the MPD server is played/paused/stopped?

I guess it's a good idea to include more useful logs, haahaa

Is the Pi music box a custom implementation of the MPD protocol? It might be an issue as i look at the procol currently case-sensitive. I added now a case-insensitive implementation of the protocol and a better logging, pushed to the main branch here. It would be awesome if you could try it out! I use the SDK 4.1.4

**Comment by mrwhale** [comment]
Nah the icon lower left says the three dots, and the play pause icons don't update. They are just the logs when in developer mode, getting them on my PC, so not sure how to get more verbose logs for you

I probably should have elaborated, pi music box is just a customised OS for the raspberry pi, that includes mopidy, mpd server and a few other nifty things, I will have a look and see the exact version of mpd it's running tonight

Awesome! Yeah I'll install that and test and let you know :D

**Comment by Sorunome** [comment]
Sorry, that `I guess it's a good idea to include more useful logs, haahaa` was meant that in my coding I should include better logs, you got all the logs that are possible to get, as far as i know ;)

**Comment by Sorunome** [comment]
So, one of my MPD servers failed to connect to, resulting in me being able to debug some more. I think I potentially fixed it in https://github.com/Sorunome/pebble-mpd-client/commit/b3ba3f02d1af972a5e923475996c9d46fedf191f
Do you want a pbw to be able to test?

Here's some info on it:
The big issue is that the MPD protocol requires TCP sockets, however, with PebbleKit JS you can only open websockets or http requests. Thus I am hacking in the protocol via http requests, before I just put them as the post body, which resulted in some server crashing the connection on the http header. Now I inject the MPD commands in the method - that which is usually GET or POST.

Be careful to paste logs now, it currently contains the password!

**Comment by mrwhale** [comment]
aah okay. Yeah that makes sense. Yes please! if you send a pbw over, I will test and report back to you!

**Comment by Sorunome** [comment]
here you go: https://files.sorunome.de/pebble-mpd-client.pbw

**Comment by mrwhale** [comment]
Thanks! So here are some logs for your viewing delight. With this build, the music doesnt seem to start now either :( I started the app, and then pressed some action buttons to get more logs

```
[19:10:40] le-mpd-client.c:378> Inited app
[19:10:40] javascript> MPD Client:392 loadScript /data/user/0/com.getpebble.android.basalt/app_js_app_files/40bd2917-1f73-462c-b428-147ba02cb9d7/pebble-js-app.js
[19:10:41] javascript> MPD Client:372 signalLoaded
[19:10:41] javascript> MPD Client:374 inside try-bridge-active
[19:10:41] javascript> MPD Client:383 signalLoaded (finalized)
[19:10:41] javascript> MPD Client:614 >> ["command_list_begin","status","currentsong","command_list_end"]
[19:10:41] javascript> MPD Client:325 JavaScript Error:
Error: Failed to execute 'open' on 'XMLHttpRequest': 'command_list_begin
status
currentsong
command_list_end
' is not a valid HTTP method.
    at Error (native)
    at XMLHttpRequest.newOpen [as open] (webview_startup.js:75:14)
    at mpdRequest (src/pkjs/index.js:136:7)
    at getInfo (src/pkjs/index.js:168:2)
    at Array.<anonymous> (src/pkjs/index.js:173:2)
    at Object.dispatchEvent (webview_startup.js:143:50)
    at signalReady (webview_startup.js:186:39)
    at <anonymous>:1:1
[19:10:41] le-mpd-client.c:163> Recieved some message....
[19:10:41] le-mpd-client.c:171> JS is ready! App Timeout: 120
[19:10:42] javascript> MPD Client:614 >> ["command_list_begin","pause 0","play","status","currentsong","command_list_end"]
[19:10:42] javascript> MPD Client:325 JavaScript Error:
Error: Failed to execute 'open' on 'XMLHttpRequest': 'command_list_begin
pause 0
play
status
currentsong
command_list_end
' is not a valid HTTP method.
    at Error (native)
    at XMLHttpRequest.newOpen [as open] (webview_startup.js:75:14)
    at mpdRequest (src/pkjs/index.js:136:7)
    at Array.<anonymous> (src/pkjs/index.js:203:4)
    at Object.dispatchEvent (webview_startup.js:143:50)
    at signalNewAppMessageData (webview_startup.js:240:25)
    at <anonymous>:1:1
[19:10:43] javascript> MPD Client:614 >> ["command_list_begin","pause 0","play","status","currentsong","command_list_end"]
[19:10:43] javascript> MPD Client:325 JavaScript Error:
Error: Failed to execute 'open' on 'XMLHttpRequest': 'command_list_begin
pause 0
play
status
currentsong
command_list_end
' is not a valid HTTP method.
    at Error (native)
    at XMLHttpRequest.newOpen [as open] (webview_startup.js:75:14)
    at mpdRequest (src/pkjs/index.js:136:7)
    at Array.<anonymous> (src/pkjs/index.js:203:4)
    at Object.dispatchEvent (webview_startup.js:143:50)
    at signalNewAppMessageData (webview_startup.js:240:25)
    at <anonymous>:1:1
[19:10:45] javascript> MPD Client:614 >> ["command_list_begin","next","status","currentsong","command_list_end"]
[19:10:45] javascript> MPD Client:325 JavaScript Error:
Error: Failed to execute 'open' on 'XMLHttpRequest': 'command_list_begin
next
status
currentsong
command_list_end
' is not a valid HTTP method.
    at Error (native)
    at XMLHttpRequest.newOpen [as open] (webview_startup.js:75:14)
    at mpdRequest (src/pkjs/index.js:136:7)
    at Array.<anonymous> (src/pkjs/index.js:212:4)
    at Object.dispatchEvent (webview_startup.js:143:50)
    at signalNewAppMessageData (webview_startup.js:240:25)
    at <anonymous>:1:1
```

**Comment by Sorunome** [comment]
Ok, that probably means my abusing of XHR doesn't quite work on android, I need to think of more abusing. (I'll work on it later today after university)

If you want to read along some more meta-information about this, go here: https://forums.pebble.com/t/pebblekit-js-raw-tcp-sockets/25042

**Comment by mrwhale** [comment]
Interesting read. I'm sure you have tried already, but can you load in an npm module for mpd client such as https://www.npmjs.com/package/mpd and use that?

**Comment by Sorunome** [comment]
That wouldn't work as they use internally the `net`\- module

**Comment by Sorunome** [comment]
So, because of the sandbox limitations, it seems like it's working for all mpd servers only on IOS and for older MPD servers on both IOS or android.

Now I have the following options:
- make a companion app to support all
- make a python script or something which proxies http connections (or websockets) to the mpd protocol which people can easily run for themself on the system they are running mpd on

which of those should I use (I think i'm more for the latter option, a python script which proxies)? Or do you have any more ideas?

**Comment by mrwhale** [comment]
I don't think creating a companion app is worth it, as some mpd clients will show as the default music in the music app on pebble anyway (mpdroid) so im sure there is one for iOS. Could you try doing the app with websockets? And have that as a dependacies for the mpd server? Instead if hacking a python script together

**Comment by Sorunome** [comment]
So, I wrote a quick python server proxy now. The files and stuff are commited, you can find the pbw for the pebble under the same URL as before. https://github.com/Sorunome/pebble-mpd-client/commit/bb4ccc726a1aec870ef1a48e7e19bbc042da5ff3

For the server proxy you will need to dump all of https://github.com/Sorunome/pebble-mpd-client/tree/master/server somewhere and run `python3 pebble_mpd_proxy.py`. It requires as dependency `python-mpd2`, run `pip3 install python-mpd2` to install it. In the config.json you can set a password which is required to use the proxy server.

I obviously still need to update the readme to include that information.

**Comment by Sorunome** [comment]
Done in https://github.com/Sorunome/pebble-mpd-client/releases/tag/1.1.0
